api:
  boot:
    security:
      away: memory
      users:
        - username: hengboy
          password: 123456
    oauth:
      enable-authorization-server: true
      away: memory
      jwt:
        enable: true
        sign-key: 123456
      # 配置多客户端
      clients:
        # 客户端test基本配置
        - client-id: test
          client-secret: 123456
          # 自定义客户端获取token的有效期
          access-token-validity-seconds: 1000
          # 自定义客户端获取refresh token的有效期，默认为30天
          refresh-token-validity-seconds: 86400
        # 客户端admin基本配置
        - client-id: admin
          client-secret: 123456
