api:
  boot:
    security:
      away: memory
      users:
        - username: hengboy
          password: 123456
    oauth:
      enable-authorization-server: true
      away: jdbc
      jwt:
        enable: true
        sign-key: 123456
